[package]
name = "extended-rational"
version = "1.1.0"
authors = ["Scott Taylor <scott11x8@gmail.com>"]

description = "Provides implementations of high-accuracy projectively-extended rational numbers."
keywords = ["rational", "extended", "number", "infinity"]

license = "MIT"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
